.gitignore

Checking out the tutorials :wink:

Adding .gitignore to exclude MacOS DS_Store from future commits

---

mock-test/custom.css

Custom Importance

---

index.html

Changed DAI to Driverless AI in Tutorials Landing Page 1.8.0

Replaced DAI with Driverless AI

---

index.html

Tutorial landing page: update to product name from Driverless to Driverless AI

Update to product name from Driverless -> Driverless AI

---

Driverless AI/ES/comenzando-con driverless-ai-test-drive/test-drive-es.md

I made some changes to the tutorial. Please go over them and let me know if you have any specific questions.

Minor updates to the tutorial in Spanish

---

Driverless AI/ES/automatic-ml-intro-test-drive-tutorial/automatic-ml-intro-test-drive-tutorial.md

Automatic Machine Learning Introduction with Driverless AI

Traducción para la sección de objetivo

---

Driverless AI/ES/automatic-ml-intro-test-drive-tutorial/automatic-ml-intro-test-drive-tutorial.md

Automatic Machine Learning Introduction with Driverless AI

Spanish Translation for the Prerequisite, Task 1, and Task 7 Section

---

Driverless AI/ES/automatic-ml-intro-test-drive-tutorial/automatic-ml-intro-test-drive-tutorial.md

Tutorial: automatic-ml-intro-test-drive-tutorial
Translated: Task 2 and Task 6

Update of automatic-ml-intro-test-drive-tutorial

---

Driverless AI/automatic-ml-intro-test-drive-tutorial/automatic-ml-intro-test-drive-tutorial.md
Driverless AI/build-your-own-custom-recipe-tutorial/build-your-own-custom-recipe-tutorial.md
Driverless AI/get-started-with-open-source-custom-recipes-tutorial/get-started-with-open-source-custom-recipes-tutorial.md
Driverless AI/getting-started-with-driverless-ai-test-drive/test-drive.md
Driverless AI/machine-learning-experiment-scoring-and-analysis/machine-learning-experiment-scoring-and-analysis.md
Driverless AI/machine-learning-interpretability-tutorial/machine-learning-interpretability-tutorial.md
Driverless AI/natural-language-processing-tutorial-sentiment-analysis/natural-language-processing-tutorial-sentiment-analysis.md
Driverless AI/time-series-recipe-tutorial-retail-sales-forecasting/time-series-recipe-tutorial-retail-sales-forecasting.md

No license requirement update for all tutorials that use Test Drive in Aquarium

Updates for all Drivereless AI Test Drive Tutorials

---

Driverless AI/PT/automatic-ml-intro-test-drive-tutorial/automatic-ml-intro-test-drive-tutorial.md

Tutorial automatic-ml-intro-with-driverlessAI

Task 4 - translation 1.0

---

Driverless AI/automatic-ml-intro-test-drive-tutorial/automatic-ml-intro-test-drive-tutorial.md
Driverless AI/machine-learning-interpretability-tutorial/machine-learning-interpretability-tutorial.md

No license requirement for Driverless AI Test Drive in Aquarium

Updates for Drivereless AI Test Drive - 

---

Driverless AI/build-your-own-custom-recipe-tutorial/build-your-own-custom-recipe-tutorial.md
Driverless AI/get-started-with-open-source-custom-recipes-tutorial/get-started-with-open-source-custom-recipes-tutorial.md
Driverless AI/machine-learning-experiment-scoring-and-analysis/machine-learning-experiment-scoring-and-analysis.md
Driverless AI/machine-learning-interpretability-tutorial/machine-learning-interpretability-tutorial.md
Driverless AI/natural-language-processing-tutorial-sentiment-analysis/natural-language-processing-tutorial-sentiment-analysis.md

No license requirement for Test Drive  in Aquarium

Updates for Drivereless AI Test Drive -

---

Driverless AI/ES/introduccion-a-machine-learning-automatico-tutorial-con-h2o.ai-test-drive/introduccion-a-machine-learning-automatico-tutorial-con-h2o.ai-test-drivel.md
Driverless AI/PT/automatic-ml-intro-test-drive-tutorial/automatic-ml-intro-test-drive-tutorial.md

These are changes done by Sergio Perez for the following tutorial: 
- automatic ml intro w test drive es translation review
There was a merge conflict since I had updated the tutorial file name.

5675sp sp/automatic ml intro w test drive es translation review

---

Driverless AI/ES/introduccion-a-machine-learning-automatico-tutorial-con-h2o.ai-test-drive/introduccion-a-machine-learning-automatico-tutorial-con-h2o.ai-test-drivel.md
Driverless AI/ES/tutorial-de-analysis-y-puntuacion-de-experimentos-de-machine-learning-enfoque-financiero/tutorial-de-analysis-y-puntuacion-de-experimentos-de-machine-learning-enfoque-financiero.md

Update to the following tutorial:
- Introduction a ML automatic con Test Drive
The file was updated due to a merge conflict when the file name was updated to Spanish.

5675sp master - Merge 2 for Intro to Auto ML w Test Drive - ES

---

Driverless AI/ES/automatic-ml-intro-test-drive-tutorial/automatic-ml-intro-test-drive-tutorial.md

Automatic Machine Learning Introduction with Driverless AI

Recomitting the translation to objective section

---

Driverless AI/ES/tutorial-de-analysis-y-puntuacion-de-experimentos-de-machine-learning-enfoque-financiero/tutorial-de-analysis-y-puntuacion-de-experimentos-de-machine-learning-enfoque-financiero.md

Revert "Tutorial 2- Scoring and Analysis - ES"

---

Driverless AI/ES/tutorial-de-analysis-y-puntuacion-de-experimentos-de-machine-learning-enfoque-financiero/tutorial-de-analysis-y-puntuacion-de-experimentos-de-machine-learning-enfoque-financiero.md

tutorial-de-analysis-y-puntuacion-de-experimentos-de-machine-learning-enfoque-financiero-es-translation

Commit for Task 6, Task 7, and Task 8

---

Driverless AI/PT/automatic-ml-intro-test-drive-tutorial/automatic-ml-intro-test-drive-tutorial.md
Driverless AI/automatic-ml-intro-test-drive-tutorial/automatic-ml-intro-test-drive-tutorial.md
README.md

Suggestions made for tutorial 1 by Lena.

Updates from HaC for tutorial Auto ML with Test Drive

---

introduction-to-machine-learning-with-h2o-3-part-2/index.html
introduction-to-machine-learning-with-h2o-3-part-3/index.html
lms/introduction-to-machine-learning-with-h2o-3-part-1/index.html
lms/introduction-to-machine-learning-with-h2o-3-part-2/index.html
lms/introduction-to-machine-learning-with-h2o-3-part-3/index.html

Fv updates

---

index.html

Update to index.html file 
- All tutorials have been redirected to the new Learning Center

Update to index file to redirect tutorials to the LMS

---

lms/automatic-ml-intro-test-drive-tutorial/custom.css
lms/build-your-own-custom-recipe-tutorial/custom.css
lms/get-started-with-open-source-custom-recipes-tutorial/custom.css
lms/getting-started-with-driverless-ai-test-drive/custom.css
lms/introduction-to-machine-learning-with-h2o-3-part-1/custom.css
lms/introduction-to-machine-learning-with-h2o-3-part-2/custom.css
lms/introduction-to-machine-learning-with-h2o-3-part-3/custom.css
lms/machine-learning-experiment-scoring-and-analysis-tutorial-financial-focus/custom.css
lms/machine-learning-interpretability-tutorial/custom.css
lms/natural-language-processing-tutorial-sentiment-analysis/custom.css
lms/scoring-pipeline-deployment-introduction/custom.css
lms/time-series-recipe-tutorial-retail-sales-forecasting/custom.css

Updates:
All tutorials custom.css files were updated

All tutorials: custom.css file updated

---

Driverless AI/PT/README.md
Driverless AI/README.md

Updated the following README.md files:
- DAI EN
- DAI ES
- DAI PT

1.9.0 Updates to DAI README.md files

---

lms/get-started-with-open-source-custom-recipes-tutorial/index.html
lms/time-series-recipe-tutorial-retail-sales-forecasting/index.html

Minor updates to Time Series Tutorial

Ac/1.9.0 updates to remaining DAI tutorials

---

Driverless AI/getting-started-with-driverless-ai-test-drive/test-drive.md

Updated images to reflect current Lab 1

---

lms/MLOps /intro-to-ml-model-deployment-and-management/codelab.json
lms/MLOps /intro-to-ml-model-deployment-and-management/index.html

"- Environment" was causing formatting errors when converting to HTML. I fixed the spacing and bolded the word so that the formatting errors would disappear.

Updated formatting for Intro to ML Deployment and Management tutorial
